server:
  port:
    8081
  servlet:
    context-path: /auth

spring:
  application:
    name:
      auth

  datasource:
    url: jdbc:mysql://localhost:3306/app_db_dev
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver

access-token:
  private-key: certs/access-private-key.pem
  public-key: certs/access-public-key.pem
refresh-token:
  private-key: certs/refresh-private-key.pem
  public-key: certs/refresh-public-key.pem

jwt:
  issuer: auth_app
  accessTokenExp: 300
  refreshTokenExp: 3600
